#!/bin/bash

SRC=src
OUT=out
ESBUILD=node_modules/.bin/esbuild

rm -rf $OUT
mkdir -p $OUT

$ESBUILD $SRC/index.ts --bundle --minify --sourcemap --outfile=$OUT/index.bundle.js

cp index.html $OUT/index.html
cp css/* $OUT/
